[Feat] ESLint import 순서 설정
boostcampwm2023/web17_morak pull request #64
Opened 2023-11-15 02:45 UTC by LEEJW1953

## 설명
- close #61 

## 완료한 기능 명세
- [x] eslint import 순서를 react > 나머지 외부 패키지 > 내부 패키지(@assets, https://github.com/components) > 상대 경로 순서로 설정한다

## 비고
- 아래 코드와 같은 `unassigned import`의 경우 순서가 맞지 않으면 경고가 발생하지만, `lint:fix` 명령어나 저장시 자동 lint 등으로 해결되지 않아서 직접 순서를 수정해야 할 것 같습니다
- 참고 : [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/order.md#warnonunassignedimports-truefalse)

  ```js
  import reactLogo from '@assets/react.svg';
  import { Header } from '@components/commons/Header';
  import '@styles/reset.css'; // unassigned import
  ```

2023-11-15 02:49 UTC, js43o approved these changes

2023-11-15 12:09 UTC, ttaerrim requested changes
외부 패키지 import 하는 경우 한번 봐 주실래요?

```javascript
/* as-is */
import { useState } from 'react';

import reactLogo from '@assets/react.svg';
import { useQuery } from '@tanstack/react-query';
import { useAtom } from 'jotai';

/* to-be */
import { useState } from 'react';
// 사이 공백은 있어도 되고 없어도 될 것 같습니다
import { useQuery } from '@tanstack/react-query';
import { useAtom } from 'jotai';

import reactLogo from '@assets/react.svg';
```

2023-11-16 00:53 UTC, LEEJW1953 commented
> 외부 패키지 import 하는 경우 한번 봐 주실래요?
> 
> ```js
> /* as-is */
> import { useState } from 'react';
> 
> import reactLogo from '@assets/react.svg';
> import { useQuery } from '@tanstack/react-query';
> import { useAtom } from 'jotai';
> 
> /* to-be */
> import { useState } from 'react';
> // 사이 공백은 있어도 되고 없어도 될 것 같습니다
> import { useQuery } from '@tanstack/react-query';
> import { useAtom } from 'jotai';
> 
> import reactLogo from '@assets/react.svg';
> ```

https://github.com/boostcampwm2023/web17_morak/pull/64/commits/f0aa3705c1ea6addf6d120bb9ef68c967f032105
수정하였습니다
사이의 공백은 있어도 되고 없어도 되도록 설정했습니다

2023-11-16 01:50 UTC, ttaerrim commented on packages/eslint-config/frontend.js
> +        'newlines-between': 'ignore',
흠 이거 그룹 별로 구분할 수 있는 게 안 되는군요 그냥 always로 다시 변경해 주실 수 있나요 ㅇ🥹

2023-11-16 02:01 UTC, ttaerrim reviewed
저희 근데 export는 정렬이 안 되네요

2023-11-16 02:40 UTC, LEEJW1953 commented on packages/eslint-config/frontend.js
> +        'newlines-between': 'ignore',
https://github.com/boostcampwm2023/web17_morak/pull/64/commits/680f195042754dfb1b7be5d3b5043087af5e1373
수정완료

2023-11-16 05:46 UTC, ttaerrim approved these changes

2023-11-16 05:46 UTC, merged