[Feat] Header 컴포넌트 구현, favicon 추가
boostcampwm2023/web17_morak pull request #71
Opened 2023-11-15 06:53 UTC by LEEJW1953

## 설명
- close #62

## 완료한 기능 명세
- [x] Header 컴포넌트 구현
- [x] `app/frontend/index.html`파일 `title`, `favicon`변경

### 스크린샷

https://github.com/boostcampwm2023/web17_morak/assets/110762136/61f55a00-b1c9-47cb-b74f-5b1b6d68a618

## 리뷰 요청 사항
- `app/frontend/src/App.tsx` 파일에서 헤더 기능 테스트를 위해 `react-router-dom`을 사용해봤습니다(추후 수정 가능)
- PR이 쌓여있어서 conflict가 날 수도 있을 것 같습니다

2023-11-15 07:02 UTC, js43o requested changes

2023-11-15 07:02 UTC, js43o commented on app/frontend/src/App.tsx
확실히 문법이 달라졌네요,,

2023-11-15 07:07 UTC, js43o requested changes

2023-11-15 07:07 UTC, js43o commented on app/frontend/src/components/commons/Header/index.css.ts
> +globalStyle('.active', {
P1: globalStyle은 전역에 적용되는 만큼 하나의 파일에 모아두면 좋을 것 같아요..! (styles/GlobalStyle.css.ts처럼)
그리고 이 경우 헤더가 아니더라도 전체 DOM에서 '.active' 클래스가 붙는 모든 요소에 해당 스타일이 적용될 것 같은데 맞나요?

2023-11-15 08:12 UTC, LEEJW1953 commented on app/frontend/src/components/commons/Header/index.css.ts
> +globalStyle('.active', {
네 지금 방법으로는  `.active` 클래스가 붙는 모든 요소에 해당 스타일이 적용되는데, `recipe`등을 사용해서 해결하는 방법을 찾아보고 있습니다

2023-11-15 08:56 UTC, ttaerrim commented on app/frontend/src/App.css.ts
> +  maxWidth: '1920px',
p2; root에 maxWidth를 설정하신 이유가 무얼까요?

2023-11-15 08:56 UTC, ttaerrim commented on app/frontend/src/App.tsx
> +          <p className={reactTheDocs}>Click on the Vite and React logos to learn more</p>
p3; 이제 이 부분은 아예 삭제해 주셔도 될 것 같네요

2023-11-15 08:56 UTC, ttaerrim commented on app/frontend/src/App.tsx
p2; 각각의 페이지마다 <Header> 태그를 넣어서 쓰는 것보다 공통으로 쓸 수 있는 Layout 컴포넌트를 만드는 것이 더 좋을 것 같아요. (이 PR에서 작업하셔도 되고, 이슈 따로 만들어서 작업하셔도 되고~)

2023-11-15 08:56 UTC, ttaerrim commented on app/frontend/src/components/commons/Header/index.css.ts
> +globalStyle('.active', {
선택된 메뉴에 active 쓰고 싶으신 거죠?

2023-11-15 08:56 UTC, ttaerrim commented on app/frontend/src/components/commons/Header/index.css.ts
> +});
```suggestion
  fontSize: '1.8rem',
});

const active = style({
  selectors: {
    [`${sideMenuButton}&`]: {
       color: vars.color.morakGreen,
       fontWeight: vars.font.weight.bold,
       fill: vars.color.morakGreen,
    }
  }
})
```

이런 식으로 쓸 수 있을 거예요. 문법 틀렸을 수 있음.
https://vanilla-extract.style/documentation/styling/#selectors
제 draft PR에도 적용했으니 참고하시면 좋을 듯합니다

2023-11-15 08:56 UTC, ttaerrim commented on app/frontend/src/components/commons/Header/index.tsx
> +          </NavLink>
p2; calendar mogaco 순서가 바뀐 것 같네요. 그리고 map 사용할 수 있을 듯합니다.

2023-11-15 08:56 UTC, ttaerrim commented on app/frontend/src/styles/reset.css.ts
> +});
👍

2023-11-15 08:57 UTC, ttaerrim commented on app/frontend/src/components/commons/Header/index.css.ts
> +  fontSize: '3rem',
p2; 이런 건 설정해 놓은 폰트 합성 사용하도록 개선할 수 있겠네요.

2023-11-15 08:58 UTC, ttaerrim reviewed
반응형도 잡아 주시나요? ㅎㅎ

2023-11-15 09:04 UTC, LEEJW1953 commented on app/frontend/src/components/commons/Header/index.css.ts
> +globalStyle('.active', {
네 맞아요

2023-11-15 09:06 UTC, LEEJW1953 commented
> 반응형도 잡아 주시나요? ㅎㅎ

논의해보시죠ㅎㅎ

2023-11-16 00:55 UTC, LEEJW1953 commented on app/frontend/src/components/commons/Header/index.css.ts
> +  fontSize: '3rem',
https://github.com/boostcampwm2023/web17_morak/pull/71/commits/66aa977352115773950193ea0cbb8532586f8e54
https://github.com/boostcampwm2023/web17_morak/pull/71/commits/30aaf3cc5f453dab2aec95017e13a917a1feedb1
폰트 설정 추가, 적용하였습니다

2023-11-16 00:56 UTC, LEEJW1953 commented on app/frontend/src/components/commons/Header/index.tsx
> +          </NavLink>
https://github.com/boostcampwm2023/web17_morak/pull/71/commits/16512ab7515024685f0da3015ae477dc92dfbe4c
수정하였습니다

2023-11-16 00:58 UTC, LEEJW1953 commented on app/frontend/src/App.tsx
> +          <p className={reactTheDocs}>Click on the Vite and React logos to learn more</p>
https://github.com/boostcampwm2023/web17_morak/pull/71/commits/f12708b520bc344b67792e29aff434725e27f29e
수정하였습니다

2023-11-16 01:32 UTC, ttaerrim commented on app/frontend/src/styles/font.css.ts
p2; 저번에 Poppins 한글 폰트가 피그마 상에서 보이는 것과 다르다는 이슈가 있어서 특정 부분에만 (아마 Morak 로고 정도) Poppins 폰트 적용하고 나머지는 Pretendard로 적용하기로 했어요!

2023-11-16 01:32 UTC, ttaerrim commented on app/frontend/src/components/commons/Header/index.tsx
> +                isActive ? `${styles.sideMenuButton} ${styles.active}` : styles.sideMenuButton
```suggestion
               `${styles.sideMenuButton} ${isActive && styles.active}`
```

2023-11-16 01:32 UTC, ttaerrim commented on app/frontend/src/components/commons/Header/index.tsx
> +const SIDE_MENU = ['mogaco', 'calendar', 'map'];
p3; 내부 아이템도 상수로 관리할 수 있겠네요

2023-11-16 01:32 UTC, ttaerrim commented on app/frontend/src/components/commons/Header/index.css.ts
> +  fontSize: '3rem',
아~ 이게 poppins 폰트였군요

2023-11-16 01:32 UTC, ttaerrim commented on app/frontend/index.html
> +    <link rel="icon" type="image/svg+xml" href="src/assets/icons/morak.svg" />
p3; svg보다 파비콘 형식으로 넣는 것이 더 좋지 않을까요?

2023-11-16 01:32 UTC, ttaerrim commented on app/frontend/index.html
> +    <title>morak</title>
모락 | 함께 모각코 
이런 식으로 들어가면 좋을 것 같은데 함께 생각해 봐요

2023-11-16 01:32 UTC, ttaerrim commented on app/frontend/src/components/commons/Header/index.css.ts
> +    fontWeight: vars.font.weight.bold,
p2; fontStyle에 poppinsBold 지정해 놓으면 fontWeight 설정은 중복 아닐까요?

2023-11-16 02:30 UTC, LEEJW1953 commented on app/frontend/index.html
> +    <link rel="icon" type="image/svg+xml" href="src/assets/icons/morak.svg" />
https://github.com/boostcampwm2023/web17_morak/pull/71/commits/81c7abd778b13d58d466393b1c3c760d3a785355
추가하였습니다

2023-11-16 02:30 UTC, LEEJW1953 commented on app/frontend/src/components/commons/Header/index.tsx
> +const SIDE_MENU = ['mogaco', 'calendar', 'map'];
https://github.com/boostcampwm2023/web17_morak/pull/71/commits/f7d9ebc97728ef846322340a6b5cac75ac8ac40f
상수로 추가하였습니다

2023-11-16 02:30 UTC, LEEJW1953 commented on app/frontend/src/components/commons/Header/index.tsx
> +                isActive ? `${styles.sideMenuButton} ${styles.active}` : styles.sideMenuButton
https://github.com/boostcampwm2023/web17_morak/pull/71/commits/f7d9ebc97728ef846322340a6b5cac75ac8ac40f
수정하였습니다

2023-11-16 02:30 UTC, LEEJW1953 commented on app/frontend/src/styles/font.css.ts
https://github.com/boostcampwm2023/web17_morak/pull/71/commits/ee912af16fedc9b7fdec20b5c9cec4807dc70a4b
수정하였습니다

2023-11-16 02:31 UTC, LEEJW1953 commented on app/frontend/src/components/commons/Header/index.css.ts
> +    fontWeight: vars.font.weight.bold,
https://github.com/boostcampwm2023/web17_morak/pull/71/commits/ee912af16fedc9b7fdec20b5c9cec4807dc70a4b
수정하였습니다

2023-11-16 02:32 UTC, js43o approved these changes

2023-11-16 07:02 UTC, ttaerrim commented on app/frontend/src/components/commons/Header/index.tsx
> +              className={({ isActive }) => (isActive ? styles.active : styles.sideMenuButton)}
p3; 그런데!! active 단독으로 쓸 거면 클래스 이름이 조금 더 구체적이어야 할 것 같네요

2023-11-16 07:11 UTC, LEEJW1953 commented on app/frontend/src/components/commons/Header/index.tsx
> +              className={({ isActive }) => (isActive ? styles.active : styles.sideMenuButton)}
https://github.com/boostcampwm2023/web17_morak/pull/71/commits/f382bece3393543bfe690f5152f4ede81f64a276
마지막 수정완료

2023-11-16 07:11 UTC, js43o approved these changes

2023-11-16 07:12 UTC, ttaerrim approved these changes

2023-11-16 07:13 UTC, merged